news/urls.py
from django.urls import path
from .views import HomeView, ArticleDetailView, submit_comment, upvote, search, downvote, inappropriate_comment, delete_comment


urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('article/<slug>', ArticleDetailView.as_view(), name='article-detail'),
    path('comment/<slug>', submit_comment, name='submit-comment'),
    path('comment_delete/<pk>', delete_comment, name='delete-comment'),
    path('upvote/<slug>', upvote, name='upvote'),
    path('search', search, name='search_posts'),
    path('downvote/<slug>', downvote, name='downvote'),
    path('inappropriate/<pk>', inappropriate_comment,
         name='inappropriate_comment'),
    ]

thedailygreen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('news.urls')),
    path('accounts/', include('allauth.urls')),
]

news/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField


class Post(models.Model):
    title = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="news_posts")
    updated_date = models.DateTimeField(auto_now=True)
    sub_headline = models.TextField()
    content = models.TextField(null=True)
    news_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    upvotes = models.ManyToManyField(User, related_name='upvoted', blank=True)
    downvotes = models.ManyToManyField(User, related_name='downvoted',
                                       blank=True)


    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return f"{self.title}"


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments')
    user_name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    comment_upvote = models.ManyToManyField(
        User, related_name='comment_upvoted', blank=True)
    comment_downvote = models.ManyToManyField(
        User, related_name='comment_downvoted', blank=True)
    inappropriate_post = models.ManyToManyField(
        User, related_name='inappropriate_posts', blank=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f"Comment {self.body} by {self.user_name}"

    def number_of_upvotes(self):
        return self.comment_upvote.count()

    def number_of_downvotes(self):
        return self.comment_downvote.count()

    def inappropriate_posts_count(self):
        return self.inappropriate_post.count()

news/forms.py
from django import forms
from news.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

news/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Post, Comment
from news.forms import CommentForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db.models import Count


class HomeView(ListView):
    model = Post
    template_name = 'home.html'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['home_news_one'] = Post.objects.all(
            ).order_by('-created_date')[0]
        context['home_news_two'] = Post.objects.all(
            ).order_by('-created_date')[1]
        context['home_news_three'] = Post.objects.all(
            ).order_by('-created_date')[2]
        context['top_five'] = Post.objects.annotate(
            upvotes_count=Count('upvotes')).order_by('-upvotes_count')[:5]
        return context


class ArticleDetailView(DetailView):
    model = Post
    form = CommentForm
    template_name = 'article_details.html'


@login_required
def submit_comment(request, slug):
    if request.method == "POST":
        user_comment = request.POST.get('body')
        comment_post = get_object_or_404(Post, slug=slug)
        user = request.user
        user_email = user.email
        user_username = user.username
        Comment.objects.create(
            post=comment_post,
            email=user_email,
            user_name=user_username,
            body=user_comment
            )
        return HttpResponseRedirect(
            reverse('article-detail', args=(comment_post.slug,)))

@login_required
def delete_comment(request, pk):
    comment=get_object_or_404(Comment, pk=pk)
    comment_post = comment.post
    if comment.user_name == request.user.username:
        comment.delete()
    return HttpResponseRedirect(
        reverse('article-detail', args=(comment_post.slug,)))

@login_required
def upvote(request, slug):
    comment_post = get_object_or_404(Post, slug=slug)
    comment_post.upvotes.add(request.user)
    return HttpResponseRedirect(
        reverse('article-detail', args=(comment_post.slug,)))


def search(request):
    search_word = request.GET.get('search_word')
    post_items = Post.objects.filter(title__icontains=search_word)
    return render(request, 'search_results.html', {'search_list': post_items})


@login_required
def downvote(request, slug):
    comment_post = get_object_or_404(Post, slug=slug)
    comment_post.downvotes.add(request.user)
    return HttpResponseRedirect(reverse('article-detail', args=(
        comment_post.slug,)))


@login_required
def inappropriate_comment(request, pk):
    flagged_comment = get_object_or_404(Comment, pk=pk)
    flagged_comment.inappropriate_post.add(request.user)
    return HttpResponseRedirect(reverse('article-detail', args=(
        flagged_comment.post.slug,)))

templates/article_details.html
{% extends 'base.html' %}
{% block title %}{{ post.slug }}{% endblock %}

{% block content %}

<h1>{{ post.title }}</h1>
<h3> By: {{ post.author }}</h3>
<h4> Last Updated: {{ post.updated_date }}</h4>
<h4> {{ post.sub_headline }}</h4><br />
<hr>

{{ post.content|safe }}
<br>
<form method="post" action="{% url 'upvote' post.slug %}">
    {% csrf_token %}

    <button class="btn btn-primary btn-sm far fa-thumbs-up btn btn-success" type="submit" name="upvote"
        value="{{ upvote.slug }}"> Upvote</button>
</form>
<p><em><small>{{ post.upvotes.count }}</small></em></p>
<br>
<form method="post" action="{% url 'downvote' post.slug %}">
    {% csrf_token %}
    <button class="btn btn-primary btn-sm far fa-thumbs-down btn btn-success" type="submit" name="downvote"
        value="{{ downvote.slug }}">Downvote</button>
</form>

<p><em><small>{{ post.downvotes.count }}</small></em></p>
<br>

<div class="col-md-8">
    {% if request.user.is_authenticated %}
    <form method="post" action="{% url 'submit-comment' post.slug %}">{% csrf_token %}
        <div class="form-group"></div>
        <textarea class="form-control" name='body' id="id_body"></textarea>


        <button type="submit" class="btn btn-success">Add Comment</button>
    </form>
    {% else %}
    <p><a id="no_line" href="{% url 'account_login' %}">Please login to comment...</a></p>
    {% endif %}
</div>

<br /><br />
<a href="{% url 'home' %}" class="btn btn-primary btn-sm btn btn-success" style="text-decoration: none">Back</a>


<h2>Comments...</h2>
    {% for comment in post.comments.all %}
    <dl>
        <dt>{{ comment.user_name }} | <small>{{ comment.created_on }}</small>
            {% if comment.user_name == request.user.username %}
            <form action="{% url 'delete-comment' comment.pk %}" method="POST">
                {% csrf_token %}
                <button class="btn btn-primary btn-sm fa fa-trash btn btn-danger" type="submit"
                    name="delete_comment"></button>
            </form>
            {% endif %}
        </dt>
        <dd>{{ comment.body }}
            <form action="{% url 'inappropriate_comment' comment.pk %}" method="POST">
                {% csrf_token %}
                <button class="btn btn-primary btn-sm far fa-frown btn btn-warning" type="submit"
                    name="innappropriate_id"></button>
            </form>
        </dd>
    </dl>

    <hr>

{% endfor %}

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  {% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    <title>{% block title %}The Daily Green{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">The Daily Green</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_login' %}">Login</a>
              </li>
              {% endif %}
              
            </ul>
            <form class="d-flex" method="GET" action="{% url 'search_posts' %}">
              <input name="search_word" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    
    <div class="container">
    {% block content %}

    {% endblock %}
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
    <script src="https://kit.fontawesome.com/10453e5d82.js" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
  {% load static %}
    {% block content %}
<br>
<h1 class="main-heading">Latest Headlines</h1>
    <div class="jumbotron p-4 p-md-5 text-white rounded btn-success">
        <div class="col-md-6 px-0">
          <h1 class="display-4 font-italic">{{ home_news_one.title }}</h1>
          <div class="lead my-3">{{ home_news_one.created_date}}</div>
          <p class="lead my-3">{{ home_news_one.sub_headline }}</p>
          <p class="lead mb-0"><a href="{% url 'article-detail' home_news_one.slug %}" class="text-white font-weight-bold" style="text-decoration: none">Continue reading...</a></p>
        </div>
      </div>
<br>
<div class="row mb-2">
  <div class="col-md-6">
    <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
      <div class="col p-4 d-flex flex-column position-static">
        <h3 class="mb-0 sub-heading">{{ home_news_two.title }}</h3>
        <div class="mb-1 text-muted">{{ home_news_two.created_date}}</div>
        <p class="card-text mb-auto">{{ home_news_two.sub_headline }}</p>
        <a href="{% url 'article-detail' home_news_two.slug %}" class="stretched-link sub-heading" style="text-decoration: none">Continue reading</a>
      </div>
      <div class="col-auto d-none d-lg-block">
        <img src="{% static 'images/solar.jpg' %}" alt="Solar Panels" width="200" height="250"/>
      </div>
    </div>
  </div>
<br>
  <div class="col-md-6">
    <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
      <div class="col p-4 d-flex flex-column position-static">
        <h3 class="mb-0 sub-heading">{{ home_news_three.title }}</h3>
        <div class="mb-1 text-muted">{{ home_news_three.created_date}}</div>
        <p class="mb-auto">{{ home_news_three.sub_headline }}</p>
        <a href="{% url 'article-detail' home_news_three.slug %}" class="stretched-link sub-heading" style="text-decoration: none">Continue reading</a>
      </div>
      <div class="col-auto d-none d-lg-block">
        <img src="{% static 'images/earth.jpg' %}" alt="Planet Earth" width="200" height="250"/>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-9">
  <h2 class="sub-heading">All News Stories</h2>
  <ul>
  {% for post in object_list %}
      <li>
        <p>
          <a href="{% url 'article-detail' post.slug %}" style="text-decoration: none" class="sub-heading"> {{ post.title }}</a> - {{ post.author }}
        </p>
        <p>
          {{ post.sub_headline }}
        </p>
      </li>

  {% endfor %}
  </ul>
  {% if is_paginated %}
  <nav aria-label="...">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link sub-heading" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="page-item disabled sub-heading"><a class="page-link sub-heading" href="#" tabindex="-1" aria-disabled="true"><span>&laquo;</span></a></li>
      {% endif %}
      {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item btn btn-primary pagination_button" aria-current="page"><span>{{ i }}<span class="sr-only"></span></span></li>
        {% else %}
          <li class="page-item sub-heading"><a class="page-link sub-heading" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link sub-heading" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true"><span>&raquo;</span></a></li>
      {% endif %}
    </ul>
    </nav>
  </div>    
  <aside class="col-md-3 blog-sidebar">
  
  <div class="p-4">
    <h4 class="font-italic sub-heading">Top 5 - Most Liked Stories</h4>
    <ol class="list-unstyled mb-0">
      {% for j in top_five %}
      <li><a href="{% url 'article-detail' j.slug %}" style="text-decoration: none" class="sub-heading">{{ j.title }}</a></li>
      {% endfor %}

    </ol>
  </div>
  </aside>
</div>

{% endif %}

{% endblock %}

templates/search_results.html
{% extends 'base.html' %}

    {% block content %}

<h1>Search Results</h1>

<ul>
{% for post in search_list %}
    <li><a href="{% url 'article-detail' post.slug %}"> {{ post.title }}</a> - {{ post.author }}
    <br/>
    {{ post.title }}</li>
    <p>
        {{ post.sub_headline }}
    </p>

{% endfor %}
</ul>


{% endblock %}